<?php
//fichier langue anglais
// Navbar
define("_ACCUEIL","Home");
define("_RESERVER_SERVICE","Book a trip");

//index.php
define("_TITRE_BODY","Body in english");
define("_TITRE_BOUTTON","Little green button!");

//Reservation trajet
define("_TITRE_RESERVATION_TRAJET","Book a trip");
define("_ADRESSE_DEPART_RESERVATION","Start location");
define("_ADRESSE_ARRIVEE_RESERVATION","End location");
define("_DATE_DEBUT_RESERVATION_TRAJET","Trip date");
define("_HEURE_DEBUT_RESERVATION_TRAJET","Trip time");
define("_BOUTTON_RESERVATION_TRAJET","Validate");

define("_TITRE_INFO1_RESERVATION","Secure trips");
define("_INFO1_RESERVATION","We take your comfort and security very seriously.");
define("_TITRE_INFO2_RESERVATION","Cheapest trips");
define("_INFO2_RESERVATION","Afordable prices for trips and services of this level of quality.");
define("_TITRE_INFO3_RESERVATION","Services");
define("_INFO3_RESERVATION","In addition to our trips, we propose a number of services to enhace your experience");

//connexion
define("_TITRE_CONNEXION","Connect to Ride in Pride");
define("_LOGIN_CONNEXION","Login");
define("_PASSWORD_CONNEXION","Password");
define("_PASSWORD_OUBLIE_CONNEXION","Password forgotten?");
define("_SOUVENIR_CONNEXION","Remember me");
define("_PAS_COMPTE_CONNEXION","You don't have an account ?");
define("_INSCRIPTION_CONNEXION","Sign in here.");
 ?>
