<?php
//fichier langue anglais
// Navbar
define("_ACCUEIL","Home");
define("_RESERVER_SERVICE","Book a trip");

//index.php
define("_TITRE_BODY","Body in english");
define("_TITRE_BOUTTON","Little green button!");
define("_TITRE_CHAUFFEUR","Our 3 best drivers!");
define("_PRIX","Price");
define("_NOTE","Rank");
define("_VOTES","Total votes");

// MODAL CHAUFFEUR
define("_VILLE","City : ");
define("_HEURE_TRAVAIL","Hours works : ");
define("_DATE_EMBAUCHE","Date of employment : ");
define("_VEHICULE","Car");
define("_MARQUE","Brand");
define("_MODELE","Model");
define("_COULEUR","Color");
define("_PLACES","Places");



//Reservation trajet
define("_TITRE_RESERVATION_TRAJET","Book a trip");
define("_ADRESSE_DEPART_RESERVATION","Start location");
define("_ADRESSE_ARRIVEE_RESERVATION","End location");
define("_DATE_DEBUT_RESERVATION_TRAJET","Trip date");
define("_HEURE_DEBUT_RESERVATION_TRAJET","Trip time");
define("_BOUTTON_RESERVATION_TRAJET","Validate");

define("_TITRE_INFO1_RESERVATION","Secure trips");
define("_INFO1_RESERVATION","We take your comfort and security very seriously.");
define("_TITRE_INFO2_RESERVATION","Cheapest trips");
define("_INFO2_RESERVATION","Afordable prices for trips and services of this level of quality.");
define("_TITRE_INFO3_RESERVATION","Services");
define("_INFO3_RESERVATION","In addition to our trips, we propose a number of services to enhace your experience");
// RESERVATION Services
define("_TITRE_SERVICE","Reservation of your services");
define("_TITRE_CHOOSE_SERVICE","Choose your services");

//connexion
define("_TITRE_CONNEXION","Connect to Ride in Pride");
define("_LOGIN_CONNEXION","Login");
define("_PASSWORD_CONNEXION","Password");
define("_PASSWORD_OUBLIE_CONNEXION","Password forgotten?");
define("_SOUVENIR_CONNEXION","Remember me");
define("_PAS_COMPTE_CONNEXION","You don't have an account ?");
define("_INSCRIPTION_CONNEXION","Sign in here.");

// Profil Navbar
define("_TITRE_NAVBAR_INFOS","My informations");
define("_TITRE_NAVBAR_ABO","My subscriptions/My company");
define("_TITRE_NAVBAR_TRAJETS","My travels");
define("_TITRE_NAVBAR_ENTREPRISE","My company");

// Profil Navbar informations
define("_TITRE_NAVBAR_INFOS_NOM","Name");
define("_TITRE_NAVBAR_INFOS_ADRESSE","Adresse");
define("_TITRE_NAVBAR_INFOS_CODE_POSTAL","Zip code");
define("_TITRE_NAVBAR_INFOS_PRENOM","First name");
define("_TITRE_NAVBAR_INFOS_DATE_NAISSANCE","Birthday");
define("_TITRE_NAVBAR_INFOS_GENRE","Gender");
define("_TITRE_NAVBAR_INFOS_EDITER","Edit");
define("_TITRE_NAVBAR_INFOS_SAUVEGARDER","Save");

// Profil Navbar Mes abonnements
define("_TITRE_NAVBAR_ABO_SOUSCRIRE","make a subscription");
define("_TITRE_NAVBAR_INFOS_QUITTER_ENTREPRISE","Leave/Delete my company");
define("_TITRE_NAVBAR_INFOS_REJOINDRE_ENTREPRISE","Join a company");
define("_TITRE_NAVBAR_INFOS_CREER_ENTREPRISE","Create a company");
define("_TITRE_NAVBAR_INFOS_VOIR_INFOS_ABONNEMENTS","Check informations about my subscription/ company");

//contact
define("_CONTACT_LET_MESSAGE","Leave us a message ! ");
define("_CONTACT_SEND_MESSAGE","'Send a message'");
define("_CONTACT_NAME", "'Your name'");
define("_CONTACT_NUM", "'Your phone number'");
define("_CONTACT_CORE_MESSAGE", "'Your message'");

 ?>
