<?php
//fichier langue francais
// Navbar
define("_ACCUEIL","Accueil");
define("_RESERVER_SERVICE","Réserver un trajet");

//index.php
define("_TITRE_BODY","Réserver votre trajet");

define("_TITRE_CHAUFFEUR","Nos 3 meilleurs chauffeurs!");
define("_PRIX","Prix");
define("_NOTE","Rang");
define("_VOTES","Votes totaux");
define("_SUR","sur");

// MODAL CHAUFFEURS
define("_VILLE","Ville d'opération : ");
define("_HEURE_TRAVAIL","Heures travaillés : ");
define("_DATE_EMBAUCHE","Date d'embauche : ");
define("_VEHICULE","Véhicules");
define("_MARQUE","Marque");
define("_MODELE","Modèle");
define("_COULEUR","Couleur");
define("_PLACES","Places");

//Reservation trajet
define("_TITRE_RESERVATION_TRAJET","Rechercher un trajet");
define("_ADRESSE_DEPART_RESERVATION","Adresse de départ");
define("_ADRESSE_ARRIVEE_RESERVATION","Adresse d'arrivée");
define("_DATE_DEBUT_RESERVATION_TRAJET","Date du trajet");
define("_HEURE_DEBUT_RESERVATION_TRAJET","Heure du trajet");
define("_BOUTTON_RESERVATION_TRAJET","Réserver");
define("_RECHERCHER","Rechercher !");

//navbar
define("_NAVBAR_INDEX","Ride in Pride");
define("_NAVBAR_ACCUEIL","Accueil");
define("_NAVBAR_ANNULER_RESERVATION","Annuler la reservation");
define("_NAVBAR_BACK_OFFICE","Back Office");
define("_NAVBAR_PROFIL","Profil");
define("_NAVBAR_CONTACT","Contactez Nous");
define("_NAVBAR_DECO","Déconnexion");
define("_NAVBAR_INSCRIPTION","Inscription");
define("_NAVBAR_CONNEXION","Connexion");

//footer
define("_FOOTER_LOCAUX","Nos locaux");
define("_FOOTER_SERVICES","Nos Services");
define("_FOOTER_INTERPRETES_COACH","Interpretes et coachs");
define("_FOOTER_VOITURE","Voitures de luxe");
define("_FOOTER_BOISSON","Boissons & nourriture");
define("_FOOTER_SOCIAL","Réseaux sociaux");
define("_FOOTER_EXP","Experience hors-norme");
define("_FOOTER_LANGUE","Langues");
define("_FOOTER_VENIR","à venir");
define("_FOOTER_PARTAGE","Partager");


// RESERVATION Services
define("_TITRE_SERVICE","Reservation de services");
define("_TITRE_CHOOSE_SERVICE","Choisissez vos services");

// RESERVATION CHAUFFEURS
define("_TITRE_CHAUFFEUR_DRIVER","Choisissez votre chauffeur");
define("_TITRE_CHAUFFEUR_TRAJET","Trajet :");
define("_TITRE_CHAUFFEUR_TRAJET_ESTIMATION","Temps de trajet estimé:");
define("_TITRE_CHAUFFEUR_TRAJET_HEURE_ARRIVE","Heure d'arrivée prévue:");


// RESERVATION TRAJET
define("_TITRE_INFO1_RESERVATION","Course sécurisée");
define("_INFO1_RESERVATION","Nous prenons trés au serieux la sécuritée et le comfort de nos clients.");
define("_TITRE_INFO2_RESERVATION","Courses le moins chères");
define("_INFO2_RESERVATION","Prix de trajet les plus abordales grâce à notre algorithme qui calcule le meilleur itinéraire.");
define("_TITRE_INFO3_RESERVATION","Services");
define("_INFO3_RESERVATION","En plus de nos courses, nous proposons des services qui améliorent votre experience");

//connexion
define("_TITRE_CONNEXION","Se connecter");
define("_LOGIN_CONNEXION","Login");
define("_PASSWORD_CONNEXION","Mot de passe");
define("_PASSWORD_OUBLIE_CONNEXION","Mot de passe oublié ?");
define("_SOUVENIR_CONNEXION","Se souvenir de moi");
define("_PAS_COMPTE_CONNEXION","Vous n'avez pas de compte ?");
define("_INSCRIPTION_CONNEXION","Inscrivez vous ici.");

// Profil Navbar
define("_TITRE_NAVBAR_INFOS","Mes informations");
define("_TITRE_NAVBAR_ABO","Mes abonnements/Mon entreprise");
define("_TITRE_NAVBAR_TRAJETS","Mes trajets");
define("_TITRE_NAVBAR_ENTREPRISE","Mon entreprise");

// Profil Navbar informations
define("_TITRE_NAVBAR_INFOS_NOM","Nom");
define("_TITRE_NAVBAR_INFOS_ADRESSE","Adresse");
define("_TITRE_NAVBAR_INFOS_CODE_POSTAL","Code postal");
define("_TITRE_NAVBAR_INFOS_PRENOM","Prénom");
define("_TITRE_NAVBAR_INFOS_DATE_NAISSANCE","Date de naissance");
define("_TITRE_NAVBAR_INFOS_GENRE","Genre");
define("_TITRE_NAVBAR_INFOS_EDITER","Editer");
define("_TITRE_NAVBAR_INFOS_SAUVEGARDER","Sauvegarder");

// Profil Navbar Mes abonnements
define("_TITRE_NAVBAR_ABO_SOUSCRIRE","Souscrire à un abonnement ");
define("_TITRE_NAVBAR_INFOS_QUITTER_ENTREPRISE","Quitter/Supprimer mon entreprise");
define("_TITRE_NAVBAR_INFOS_REJOINDRE_ENTREPRISE","Rejoindre une entreprise");
define("_TITRE_NAVBAR_INFOS_CREER_ENTREPRISE","Créer une entreprise");
define("_TITRE_NAVBAR_INFOS_VOIR_INFOS_ABONNEMENTS","Voir les informations de mon abonnement");


//Contact
define("_CONTACT_LET_MESSAGE","Laissez nous un message ! ");
define("_CONTACT_SEND_MESSAGE","'Envoyez un message'");
define("_CONTACT_NAME", "'Votre nom'");
define("_CONTACT_NUM", "'Votre numero de téléphone'");
define("_CONTACT_CORE_MESSAGE", "'Votre message'");

//driver index
define("_DRIVER_COMPETANT","DES COLLABORATEURS COMPETENTS");
define("_DRIVER_TITRE","Les meilleurs chaufferus");
define("_PRICE", "Prix");
define("_SUR_VOTE", "sur");
define("_DRIVER_INFO", "PLUS D'INFORMATION");

// Informations modal CHAUFFEUR
define("_DRIVER_INFO_VILLE", "Ville d'operation : ");
define("_DRIVER_INFO_HEURE", "Heures Travailées : ");
define("_DRIVER_INFO_DATE", "Date d'embauche : ");

define("_DRIVER_INFO_MARQUE", "Marque : ");
define("_DRIVER_INFO_MODELE", "Modèle : ");
define("_DRIVER_INFO_COULEUR", "Couleur : ");
define("_DRIVER_INFO_PLACES", "Places : ");

define("_DRIVER_INFO_VEHICULE", "Véhicule : ");

define("_DRIVER_INFO_DESCRIPTION", "Description : ");
define("_DRIVER_INFO_CHOISIR_DRIVER", "Choisir : ");
define("_DRIVER_INFO_VALIDER_DRIVER", "Valider :");

 ?>
