<?php
//fichier langue francais
// Navbar
define("_ACCUEIL","Accueil");
define("_RESERVER_SERVICE","Réserver un trajet");

//index.php
define("_TITRE_BODY","Body en francais");
define("_TITRE_BOUTTON","Petit boutton vert!");
define("_TITRE_CHAUFFEUR","Nos 3 meilleurs chauffeurs!");
define("_PRIX","Prix");
define("_NOTE","Rang");
define("_VOTES","Votes totaux");

// MODAL CHAUFFEURS
define("_VILLE","Ville d'opération : ");
define("_HEURE_TRAVAIL","Heures travaillés : ");
define("_DATE_EMBAUCHE","Date d'embauche : ");
define("_VEHICULE","Véhicules");
define("_MARQUE","Marque");
define("_MODELE","Modèle");
define("_COULEUR","Couleur");
define("_PLACES","Places");

//Reservation trajet
define("_TITRE_RESERVATION_TRAJET","Rechercher un trajet");
define("_ADRESSE_DEPART_RESERVATION","Adresse de départ");
define("_ADRESSE_ARRIVEE_RESERVATION","Adresse d'arrivée");
define("_DATE_DEBUT_RESERVATION_TRAJET","Date du trajet");
define("_HEURE_DEBUT_RESERVATION_TRAJET","Heure du trajet");
define("_BOUTTON_RESERVATION_TRAJET","Réserver");
// RESERVATION Services
define("_TITRE_SERVICE","Reservation de services");
define("_TITRE_CHOOSE_SERVICE","Choisissez vos services");

// RESERVATION TRAJET
define("_TITRE_INFO1_RESERVATION","Course sécurisée");
define("_INFO1_RESERVATION","Nous prenons trés au serieux la sécuritée et le comfort de nos clients.");
define("_TITRE_INFO2_RESERVATION","Courses le moins chères");
define("_INFO2_RESERVATION","Prix de trajet les plus abordales grâce à notre algorithme qui calcule le meilleur itinéraire.");
define("_TITRE_INFO3_RESERVATION","Services");
define("_INFO3_RESERVATION","En plus de nos courses, nous proposons des services qui améliorent votre experience");

//connexion
define("_TITRE_CONNEXION","Se connecter");
define("_LOGIN_CONNEXION","Login");
define("_PASSWORD_CONNEXION","Mot de passe");
define("_PASSWORD_OUBLIE_CONNEXION","Mot de passe oublié ?");
define("_SOUVENIR_CONNEXION","Se souvenir de moi");
define("_PAS_COMPTE_CONNEXION","Vous n'avez pas de compte ?");
define("_INSCRIPTION_CONNEXION","Inscrivez vous ici.");

// Profil Navbar
define("_TITRE_NAVBAR_INFOS","Mes informations");
define("_TITRE_NAVBAR_ABO","Mes abonnements/Mon entreprise");
define("_TITRE_NAVBAR_TRAJETS","Mes trajets");
define("_TITRE_NAVBAR_ENTREPRISE","Mon entreprise");

// Profil Navbar informations
define("_TITRE_NAVBAR_INFOS_NOM","Nom");
define("_TITRE_NAVBAR_INFOS_ADRESSE","Adresse");
define("_TITRE_NAVBAR_INFOS_CODE_POSTAL","Code postal");
define("_TITRE_NAVBAR_INFOS_PRENOM","Prénom");
define("_TITRE_NAVBAR_INFOS_DATE_NAISSANCE","Date de naissance");
define("_TITRE_NAVBAR_INFOS_GENRE","Genre");
define("_TITRE_NAVBAR_INFOS_EDITER","Editer");
define("_TITRE_NAVBAR_INFOS_SAUVEGARDER","Sauvegarder");

// Profil Navbar Mes abonnements
define("_TITRE_NAVBAR_ABO_SOUSCRIRE","Souscrire à un abonnement ");
define("_TITRE_NAVBAR_INFOS_QUITTER_ENTREPRISE","Quitter/Supprimer mon entreprise");
define("_TITRE_NAVBAR_INFOS_REJOINDRE_ENTREPRISE","Rejoindre une entreprise");
define("_TITRE_NAVBAR_INFOS_CREER_ENTREPRISE","Créer une entreprise");
define("_TITRE_NAVBAR_INFOS_VOIR_INFOS_ABONNEMENTS","Voir les informations de mon abonnement");


//Contact
define("_CONTACT_LET_MESSAGE","Laissez nous un message ! ");
define("_CONTACT_SEND_MESSAGE","'Envoyez un message'");
define("_CONTACT_NAME", "'Votre nom'");
define("_CONTACT_NUM", "'Votre numero de téléphone'");
define("_CONTACT_CORE_MESSAGE", "'Votre message'");


 ?>
