<?php
//fichier langue francais
// Navbar
define("_ACCUEIL","Accueil");
define("_RESERVER_SERVICE","Réserver un trajet");

//index.php
define("_TITRE_BODY","Body en francais");
define("_TITRE_BOUTTON","Petit boutton vert!");

//Reservation trajet
define("_TITRE_RESERVATION_TRAJET","Rechercher un trajet");
define("_ADRESSE_DEPART_RESERVATION","Adresse de départ");
define("_ADRESSE_ARRIVEE_RESERVATION","Adresse d'arrivée");
define("_DATE_DEBUT_RESERVATION_TRAJET","Date du trajet");
define("_HEURE_DEBUT_RESERVATION_TRAJET","Heure du trajet");
define("_BOUTTON_RESERVATION_TRAJET","Réserver");

define("_TITRE_INFO1_RESERVATION","Course sécurisée");
define("_INFO1_RESERVATION","Nous prenons trés au serieux la sécuritée et le comfort de nos clients.");
define("_TITRE_INFO2_RESERVATION","Courses le moins chères");
define("_INFO2_RESERVATION","Prix de trajet les plus abordales grâce à notre algorithme qui calcule le meilleur itinéraire.");
define("_TITRE_INFO3_RESERVATION","Services");
define("_INFO3_RESERVATION","En plus de nos courses, nous proposons des services qui améliorent votre experience");

//connexion
define("_TITRE_CONNEXION","Se connecter");
define("_LOGIN_CONNEXION","Login");
define("_PASSWORD_CONNEXION","Mot de passe");
define("_PASSWORD_OUBLIE_CONNEXION","Mot de passe oublié ?");
define("_SOUVENIR_CONNEXION","Se souvenir de moi");
define("_PAS_COMPTE_CONNEXION","Vous n'avez pas de compte ?");
define("_INSCRIPTION_CONNEXION","Inscrivez vous ici.");


 ?>
